[package]
name = "raft"
version = "0.1.0"
authors = ["nooberfsh"]

[dependencies]
grpcio = "0.2"
protobuf = "1.4"
futures = "0.1"
serde = "1.0"
serde_derive = "1.0"
log = "0.4"
tokio-core = "0.1"


[dependencies.worker]
version = "*"
git = "https://github.com/nooberfsh/worker.git"
